openqaoa/backends/__init__.py
=> Dev braket jobs

docs/source/problems.rst, openqaoa/backends/qpus/qaoa_pyquil_qpu.py, openqaoa/workflows/optimizer.py, tests/test_optimisers.py
- Removed Duplicates found in `dev`
NULL
=> Fixed Duplicates

openqaoa/optimizers/result.py, tests/test_qpu_devices.py
Once we find the minimum of the QAOA cost function, we can access the most probable state. However, in many cases, it is not the solution with the minimum Hamiltonian cost from the set of bitstring outcomes. The additional function, I'm adding gives the bitstring with the minimum Hamiltonian cost.
=> adding a best solution for raw data

.github/workflows/test.yml, openqaoa/cost_function.py, setup.py, tests/test_qpu_devices.py
- `cvar_expectation_value_classical` method had a bug while computing the fraction of counts to be used for computing the expectation value. This PR fixes that bug
=> bugfix to cvar_expectation_value_classical

docs/source/faq.rst, openqaoa/basebackend.py, openqaoa/qaoa_parameters/baseparams.py, openqaoa/qaoa_parameters/operators.py
- Added FAQ to ReadtheDocs Source
- Updated Docstrings for a couple of files.
test_all.py
=> Updated FAQ and Some Docstrings

.github/workflows/codeql.yml, .github/workflows/publish.yml, .github/workflows/test_dev.yml, .github/workflows/test_main_linux.yml, .github/workflows/test_main_windows.yml, docs/source/index.rst, openqaoa/_version.py, setup.py, tests/test_notebooks.py, tests/test_pyquil_qvm.py, tests/test_qpu_devices.py, tests/test_qpu_qiskit.py
- Hotfix lowering the requirement for matplotlib;|
- Update github actions accordingly
=> fix matplotlib dependency

CHANGELOG.md, README.md
Update readme badge and changelog
=> update readme badge and changelog

openqaoa/qaoa_parameters/annealingparams.py, openqaoa/qaoa_parameters/baseparams.py, openqaoa/qaoa_parameters/extendedparams.py, openqaoa/qaoa_parameters/fourierparams.py, openqaoa/qaoa_parameters/standardparams.py, tests/test_parameters_plots.py
Fixed the .plot method for the varational params class
=> fixed varational params plot method

.github/workflows/publish.yml, .github/workflows/test_dev.yml, .github/workflows/test_main_linux.yml, .github/workflows/test_main_windows.yml, setup.py
- Hotfix to setup.py missing comma.
- Hotfix to test_dev.yml
NIL
=> Dev hotfix setup

tests/test_qpu_devices.py
=> Bugfix Test Devices AWS

codecov.yml, openqaoa/devices.py, tests/test_qpu_devices.py
- Added `aws_region` and `s3_bucket_name` in initialisation parameters for `DeviceAWS`
- Updated `create_device` method for newer initialisation parameters
- Updated codecov.yml target
=> Updated DevicAWS

openqaoa/optimizers/optimization_methods.py, openqaoa/optimizers/qaoa_optimizer.py, openqaoa/utilities.py, openqaoa/workflows/optimizer.py
- Update to `get_optimizer` method for better error messages
- Bugfix for `hamiltonian_from_graph` method inside `utilities.py`
[//]: <> (- [x] My code follows the style guidelines of this project)
=> Dev hotfix for optimizer and utilties bugs

examples/03_qaoa_on_qpus.ipynb, examples/11_Mixer_example.ipynb, tests/test_notebooks.py
- Updated notebook_test for Mixer Example Notebook.
- Updated notebook header.
=> Bugfix notebook test

openqaoa/backends/qpus/qaoa_qiskit_qpu.py
- Bugfix for Error Message
- Bugfix for initial_layout in Qiskit Backend.
=> Bugfix: Error message displaying wrongly and initial_layout exception

.github/workflows/test_main_macos.yml, .github/workflows/test_main_windows.yml
=> Add macos tests to main

openqaoa/qaoa_parameters/gatemap.py, openqaoa/qaoa_parameters/hamiltonianmapper.py, openqaoa/utilities.py
- Updated Docstrings in `hamiltonianmapper.py`, `gatemap.py` and `utilities.py.`
=> Updated docstrings

openqaoa/backends/intermediate_representations/qaoa_intermediate_representations.py
- `pyqir` imports were problematic after new [upgrade](https://www.qir-alliance.org/pyqir/upgrade.html)
- Added commented-out method`convert_to_bitcode` with the exact same structure as `convert_to_ir`
-   Decided to comment it out until issue with IR results is resolved
=> Fixed pyqir imports and added provisional bitcode function

tests/test_imports.py, tests/test_optimizers.py
=> Added unittests for new folder structure

openqaoa/backends/simulators/qaoa_analytical_sim.py, openqaoa/backends/simulators/qaoa_pyquil_sim.py, openqaoa/backends/simulators/qaoa_qiskit_sim.py, openqaoa/backends/simulators/qaoa_vectorized.py, openqaoa/basebackend.py, openqaoa/optimizers/training_vqa.py, openqaoa/qaoa_parameters/baseparams.py, openqaoa/utilities.py, tests/test_backends.py, tests/test_derivative.py
We are now rounding the expecation values and parameters to the 8th decimal
=> Precission errors

src/openqaoa-core/algorithms/rqaoa/rqaoa_workflow.py, tests/test_analytical_simulator.py
Bool variable analytical controlling whether computing the expectation values using the analytical formula or from the dict count. 
Note that the backend cannot be checked in utilities.py due to a circular import.
=> analytical=True only if using the analytical simulator

examples/09_RQAOA_example.ipynb, examples/X_dumping_data.ipynb, src/openqaoa-core/algorithms/baseworkflow.py, src/openqaoa-core/algorithms/qaoa/qaoa_result.py, src/openqaoa-core/algorithms/qaoa/qaoa_workflow.py, src/openqaoa-core/algorithms/rqaoa/rqaoa_results.py, src/openqaoa-core/algorithms/rqaoa/rqaoa_workflow.py, src/openqaoa-core/optimizers/qaoa_optimizer.py, tests/test_results.py, tests/test_workflows.py
workflows: 
QAOA and RQAOA results:
```
maxcut_qubo = MaximumCut(nx.generators.fast_gnp_random_graph(n=6,p=0.6, seed=42)).get_qubo_problem()
device = create_device(location='local', name='qiskit.shot_simulator')
q = QAOA()
q.set_device(device)
q.set_circuit_properties(p=1, param_type='extended', init_type='rand', mixer_hamiltonian='x')
q.set_backend_properties(prepend_state=None, append_state=None)
q.set_classical_optimizer(maxiter=10, optimization_progress=True)
q.set_exp_tags({'a': 1, 'b': 2})
q.compile(maxcut_qubo) 
q.optimize() 
q_asdict = q.asdict()
q_json = q.dumps()
q.dump(file_name='qaoa.json', file_path='./x/', prepend_id=False)
q_from_dict         = QAOA.from_dict(q_asdict)
q_from_json_string  = QAOA.loads(q_json)
q_from_json_file    = QAOA.load(file_name='qaoa.json', …
```
=> from_dict and load(s) methods for workflows

src/openqaoa-qiskit/backends/qaoa_qiskit_qpu.py, tests/test_qpu_qiskit.py
- Hotfix for Qiskit QAOA circuit return value
- Added two new unit-tests
=> hotfix to main tests

.readthedocs.yml
=> Hotfix main docs

src/openqaoa-core/openqaoa/algorithms/baseworkflow.py, src/openqaoa-core/openqaoa/algorithms/workflow_properties.py, src/openqaoa-core/openqaoa/backends/qaoa_backend.py, src/openqaoa-qiskit/openqaoa_qiskit/backend_config.py, src/openqaoa-qiskit/openqaoa_qiskit/backends/qaoa_qiskit_qpu.py
- Qiskit QPU backend has a new option `qiskit_optimization_level` that lets users specify the optimization level of the `qiskit.transpile` function.
=> added qiskit optimziation level option

.github/workflows/test_dev_ext.yml
=> Hotfix Update test_dev_ext.yml

Makefile, src/openqaoa-core/openqaoa/backends/plugin_finder.py, src/openqaoa-qiskit/requirements.txt
=> Dev: fixing makefile

.github/workflows/test_main_linux.yml, .github/workflows/test_main_macos.yml, .github/workflows/test_main_windows.yml
=> Dev update yml

src/openqaoa-core/tests/test_bin_packing.py, src/openqaoa-core/tests/test_portfolio_optimization.py, src/openqaoa-core/tests/test_sk.py, src/openqaoa-core/tests/test_tsp.py, src/openqaoa-core/tests/test_vrp.py
=> Fixed problems test

src/openqaoa-core/openqaoa/backends/plugin_finder.py, src/openqaoa-core/requirements.txt, src/openqaoa-core/requirements_test.txt
- Moved ipython requirement to general `requirements.txt`
=> fix regular requirements for openqaoa

src/openqaoa-qiskit/tests/test_qpu_qiskit.py
- **Fixes tests for QPU `ibmq_manila`**
=> Fixed unsupported ibmq_manila in test
