entropicalabs/openqaoa

openqaoa/problems/problem.py, tests/test_problems.py
`Knapsack` and `SlackFreeKnapsack` problem classes convert a Knapsack problem into a QUBO problem solvable using QAOA. They also include a `random_instance(n_items)` method to generate a problem randomly. This method failed in the case of the randomly generated list of item weights being all equal. 
This was due to `weight_capacity` selected randomly between `np.min(weights), np.max(weights)`. However, in the all-equal case, this statement breaks. The fix takes care of this edge case.
- **Fixes [#48](/entropicalabs/openqaoa/issues/48)**
=> added fix to knapsack and slackfreeknapsack random_instance

openqaoa/problems/converters.py, setup.py, tests/test_converters.py
Adding functionality to translate docplex problems into its QUBO representation for OpenQAOA. This function allows to write objective functions with their respective equality and inequality constraints and transform them into its QUBO representation. They corresponds to #36 and #41.
In #36 and #41 there are explanations of this approach.
- List any dependencies that are required for this change, if any. `docplex`
- **Fixes #36**
[//]: <> (- [x] My code follows the style guidelines of this project)
`test_converters.py`
=> From Docplex to Ising Model (QUBO)

openqaoa/qaoa_parameters/gatemap.py
- Some fixed angles for the gates in GateMap decomposition are specified directly as numeric values. This breaks the code when these GateMap objects use any decomposition other than `trivial`. This can be quickly rectified by wrapping these numeric angles inside a RotationAngle object. This PR implements this fix
=> bugfix numeric angles need to be specified as RotationAngle objects too

openqaoa/optimizers/training_vqa.py, openqaoa/workflows/optimizer.py, openqaoa/workflows/parameters/qaoa_parameters.py
- Proper indentation to allow `save_intermediate` feature to be used in backends that have no job ids
- Add `save_intermediate` to the standard QAOA workflow
- Updated docstring for QAOA workflow class
test_all.py
=> Bugfix: save_intermediate doesnt work for backends with no jobid

openqaoa/backends/qpus/qaoa_pyquil_qpu.py
- Hotfix for Rigetti QPUs accessed through QCS.
- Retrieve declarations through parametric_circuit instead of prog_exe since EncryptedPrograms (generated by pyQuil only when using QPUs) do not have the declarations property.
- [x ] I have performed a self-review of my code.
- [x ] My changes generate no new warnings
=> Hotfix for Rigetti QPUs accessed through QCS

openqaoa/workflows/optimizer.py, tests/test_workflows.py
Before, if one optimized twice a RQAOA object, the second time wasn't working as expected. Because the self._q.was compiled with the last problem of the first optimization.
=> Bugfix: Running .optimize() for a RQAOA object not working as expected

docs/source/backends.rst, docs/source/workflows.rst
Quick changes to documentation organization:
- RQAOA workflows is part of workflows section
- Changes in organization of backends and devices
=> couple of cosmetic fixes to docs

README.md, docs/source/index.rst
Oxford Quantum Circuits was listed as OCQ instead of OQC.
Minor documentation fixes to correct spelling of Oxford Quantum Circuits, was listed as OCQ but should be OQC. No dependencies changed.
- [N/A] I have commented my code and used numpy-style docstrings
- [N/A] I have made corresponding updates to the documentation.
- [N/A] I have added/updated tests to make sure bugfix/feature works.
- [N/A] New and existing unit tests pass locally with my changes.
Ran `pytest tests/` and ensure test output was the same before and after the change.
=> fix: Spelling of Oxford Quantum Circuits

openqaoa/problems/problem.py, tests/test_problems.py
This PR implements the methods:
`QUBO.from_dict()`
and
`Problem.from_instance_dict()`
Example:
```
from openqaoa.problems.problem import NumberPartition, Problem, QUBO
problem = NumberPartition.random_instance(n_numbers=4)
qubo = problem.get_qubo_problem()
qubo.set_metadata({'tag1': 'value1', 'tag2': 'value2'})
qubo_asdict = qubo.asdict()
qubo_fromdict = QUBO.from_dict(qubo_asdict)
problem_instance = qubo_asdict['problem_instance']
problem_fromdict = Problem.from_instance_dict(problem_instance)
#check that we got the same objects
print(qubo.__dict__, qubo_fromdict.__dict__)
print(problem.__dict__, problem_fromdict.__dict__)
```
=> QUBO / Problem from dict

openqaoa/optimizers/result.py, openqaoa/rqaoa/rqaoa_results.py, openqaoa/workflows/optimizer.py, tests/test_workflows.py
In this PR changes to the dump(s) methods and the way we save the data/files will be implemented.
The header has been already changed, now when we dump the data we find something like:
```
'header'{
...,
'metadata': {'tag1': 'value1',
'tag2': 'value2',
'problem_type': 'maximum_cut',
'key1': 'value1',
'key2': 'value2',
'backend_n_shots': 100,
'optimizer_method': 'nelder-mead',
'optimizer_jac': 'finite_difference',
'optimizer_hess': 'finite_difference',
'circuit_param_type': 'standard',
'circuit_init_type': 'rand',
'circuit_p': 2,
'rqaoa_type': 'adaptive',
'rqaoa_n_max': 1,
'rqaoa_n_cutoff': 3}
}
```
=> Changing data saving workflows methods

docs/source/index.rst
code snipset of index.rst updated
=> fix index.rst docs

src/openqaoa-core/utilities.py, tests/test_utilities.py
The energy_expectation() function in utilities.oy did not account for constant terms, and the respective test wasa ring of disagrees Hamiltonian with vanishing constant.
I have fixed the issue by adding the constant after the averaging, I have modified the current test by adding a constant term to the ring of disagrees Hamiltonian and added a second test on a Minimum Vertex Cover Hamiltonian.
- Bug fix (non-breaking change which fixes an issue)
Modified test_utilities.py as per in the description
=> Bug Fix: Added missing constant term contribution in energy_expectation

src/openqaoa-core/backends/qaoa_device.py
Before when running:
``
device = create_device(location='test', name='vectorized')
``
you got a warning like:
> _Invalid device location, Choose from: 'test'_
it was returning the input.
I have modified that so that the warning that you get is:
> _Invalid device location, Choose from: ['ibmq', 'qcs', 'aws', 'local', 'azure']_
=> Fix warning: invalid location

src/openqaoa-core/algorithms/baseworkflow.py, tests/test_workflows.py
The dump method was giving the following name:
`{experiment_id}--{atomic_id}`
the correct one is:
`{project_id}--{experiment_id}--{atomic_id}`
=> fixed file name dump method workflows

src/openqaoa-qiskit/backends/qaoa_qiskit_qpu.py
- bugfix in `qaoa_qiskit_qpu.py`. The method `qaoa_circuit` did not return the transpiled_circuit.
=> bugfix in qaoa_circuit in qiskit backend

.github/workflows/test_dev.yml, setup.py, src/openqaoa-qiskit/backends/devices.py, src/openqaoa-qiskit/backends/qaoa_qiskit_qpu.py, tests/test_qpu_devices.py
- Added `qiskit_ibm_provider` to `setup.py`
- Fixed Qiskit's deprecation warning
- Changed `IBMQ` import to `IBMProvider`.
- Updated `DeviceQiskit` to accommodate assembling of instance string for `IBMProvider`
- Updated Exceptions in Qiskit QPU Backend to import from `qiskit_ibm_provider`
- Updated unittest `test_changing_provider` in `test_qpu_devices.py`
- Updated `test_dev.yml` for new `save_account` through `IBMProvider`
=> Fixing Deprecation Warning

src/openqaoa-core/qaoa_components/ansatz_constructor/operators.py, tests/test_operators.py, tests/test_qpu_devices.py
- Added new method to `Hamiltonian` object that constructs a dictionary of terms (either `PaulIOp`s or qubit indices) and coefficients of the Hamiltonian object
- added `__hash__` method to PauliOp class, and fixed the `__eq__` method.
[//]: <> (- [x] My code follows the style guidelines of this project)
Added a new unit-test in `test_operators.py` file to test the new method
=> added new dictionary method to Hamiltonian class, and few other updates

.github/workflows/test_main_linux.yml, src/openqaoa-core/algorithms/baseworkflow.py, src/openqaoa-core/algorithms/qaoa/qaoa_result.py, src/openqaoa-core/algorithms/qaoa/qaoa_workflow.py, src/openqaoa-core/algorithms/rqaoa/rqaoa_result.py, src/openqaoa-core/algorithms/rqaoa/rqaoa_utils.py, src/openqaoa-core/algorithms/rqaoa/rqaoa_workflow.py, src/openqaoa-core/algorithms/rqaoa/rqaoa_workflow_properties.py, tests/jobs_test_input/input_data/openqaoa_params.json, tests/test_backends.py, tests/test_benchmark.py, tests/test_circuit_routing.py, tests/test_notebooks.py, tests/test_qpu_braket.py, tests/test_qpu_qiskit.py, tests/test_workflows.py
Bug Fixes and Enhancements:
- `q.dump` was not working for some backends. The issue was the wrong serialization of numpy values (measurement results and costs, both in the intermediate and in the optimized result)
- Target and Cloud in the header are now automatically inferred
- Some standard QAOA values are automatically added to the header's metadata
- function naming
- variable names
- fix some issues related to flake8 
- [x I have added/updated tests to make sure bugfix/feature works.
=> Bugfix dump methods

src/openqaoa-core/algorithms/qaoa/qaoa_workflow.py
- Now  the QAOA workflow class contains the method `solve_brute_force()` that calls the `ground_state_hamiltonian` function from `openqaoa.utilities`. 
- Results are stored as a dictionary in `self.brute_force_results` and can be printed out with the `verbose` flag.
- The parameter `bounded` imposes the artificial limit of 25 qubits to prevent memory overflow
- **Fixes # 234**
=> Fixing issue #234: Brute force solver as OpenQAOA workflow class method

tests/test_workflows.py
Added tests for PR #239 by @GiacomoFrn. 
The new tests check that:
- The brute force gives gives the same results are `ground_state_hamitonian`
- The brute force method raises an error when the QAOA is uncompiled
- If `bounded=True` we do not brute force for a number of qubits > 25
(Closed my previous PR #240 due to synchronization issues)
In `test_workflows.py`: Added `test_qaoa_brute_force`
=> Add Brute Force Tests

src/openqaoa-core/openqaoa/algorithms/qaoa/qaoa_result.py, src/openqaoa-core/tests/test_results.py
This PR is for solving issue https://github.com/entropicalabs/openqaoa/issues/235.
test_qaoa_results_calculate_statistics_full, test_qaoa_results_calculate_statistics_without_intermediate, test_qaoa_results_calculate_statistics_raise_value_error.
=> Add result statistics on measurement outcomes in QAOAResult object

pytest.ini, src/openqaoa-core/openqaoa/algorithms/qaoa/qaoa_workflow.py, src/openqaoa-core/openqaoa/algorithms/rqaoa/rqaoa_workflow.py, src/openqaoa-core/openqaoa/backends/basebackend.py
This PR is for solving issue https://github.com/entropicalabs/openqaoa/issues/233.
By running tests locally for openqaoa-azure and openqaoa-core.
=> Prevent double authentication while using openqaoa-azure

src/openqaoa-qiskit/tests/test_qiskit_backend_wrapper.py
- Marked a unittest in Twirling unittests for qiskit with `qpu` as the tests requires IBM QPU credentials to run.
=> Added mark to twirling unittest

src/openqaoa-braket/openqaoa_braket/backends/devices.py
- Fixed `DeviceAWS.connectivity() method to consistently return a `List[List[int]]` same as other backends.
=> corrected connectivity output of aws device

src/openqaoa-core/openqaoa/algorithms/qaoa/qaoa_workflow.py, src/openqaoa-core/tests/test_workflows.py, src/openqaoa-qiskit/openqaoa_qiskit/backends/devices.py
- I fixed a known issue that the SPAM twirling feature has not implemented `expectation_with_uncertainty()`, calling `evaluate_circuit()` would not call the wrapper's redefinition of `expectation()` with the previous version of this code.
- The function `evaluate_circuit()` now functions correctly, further implementation of the uncertainty calculation with SPAM twirling is still possible.
[/]: <> (- [ ] Any dependent changes have been merged and published in downstream modules)
=> Dev spam twirling evaluate

src/openqaoa-core/openqaoa/problems/binpacking.py, src/openqaoa-core/openqaoa/problems/portfoliooptimization.py, src/openqaoa-core/openqaoa/problems/qubo.py, src/openqaoa-core/openqaoa/problems/sherrington_kirkpatrick.py, src/openqaoa-core/openqaoa/problems/tsp.py, src/openqaoa-core/openqaoa/problems/vehiclerouting.py, src/openqaoa-core/tests/test_qubo.py
=> Fixing tests QUBO and typing

.github/workflows/test_dev.yml, .github/workflows/test_main_linux.yml
=> Updated key names for AWS cli

.github/workflows/test_dev.yml, .github/workflows/test_main_linux.yml, .github/workflows/test_main_macos.yml, .github/workflows/test_main_windows.yml, Makefile, examples/community_tutorials/02_docplex_example.ipynb, setup.py, tests/test_imports.py
- Remove the inclusion of `openqaoa-pyquil` from the meta package
Using regular tests, pyquil tests may be ignored when testing the meta-package
=> Removed pyquil from global package
